spring.application.name=moneymanagement
spring.datasource.url=jdbc:postgresql://dpg-d98j82cs728c73dhp5ng-a.singapore-postgres.render.com/moneymanager_v570
spring.datasource.username=moneymanager_v570_user
spring.datasource.password=MheLY6iRmnT8OulROgOLVkTnxR2p6l7t
